FROM python:3.12.3

# Setting the working directory within the container
WORKDIR /app

# Copying the current working dir into the /app folder
COPY . /app

# On starting, what should the container do ...
ENTRYPOINT ["python", "demo_leve11.py"]